name: Fetch RSS and Update XML

on:
  schedule:
    - cron: '0 * * * *'  # この行は毎時実行する設定だよ、変更する場合はこの行を修正してね！
  workflow_dispatch:  # この行を追加すると、手動で実行することもできるようになるよ！

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Pythonのバージョンを指定するよ！

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser

    - name: Fetch RSS and Update XML
      run: python makeRSS_GoogleNews.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (
          git commit -m "Updated XML with new RSS entries" &&
          git push https://${{secrets.MY_SECRET_TOKEN}}@github.com/${{github.repository}}.git
        )

